apiVersion: v1
kind: ConfigMap
metadata:
  name: opa-envoy-config
  namespace: auth
data:
  config.yaml: |
    plugins:
      envoy_ext_authz_grpc:
        addr: :9191
        path: envoy/authz/allow
    decision_logs:
      console: true