apiVersion: v1
kind: Pod
metadata:
  labels:
    run: auther-app
  name: auther-app
  namespace: auth
spec:
  containers:
  - image: gcr.io/devops-projects-20210212/auth-app:v1.0.1
    name: auther
    ports:
      - containerPort: 8080
    env:
      - name: APP_PORT
        value: "8080"
      - name: KEY_URL
        value: http://keycloak-svc:8080/auth/realms/demo/protocol/openid-connect/token
      - name: CLIENT_ID
        value: demo_application
      - name: CLIENT_SECRET
        value: e420306e-333c-4648-9e52-676d6e9e3ea2
      - name: SVC_URL
        value: http://external-svc:8080/externalservice
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
