apiVersion: v1
kind: Service
metadata:
  labels:
    istio.io/rev: default
    run: auther-app
    security.istio.io/tlsMode: istio
    service.istio.io/canonical-name: external-app
    service.istio.io/canonical-revision: latest
  name: external-svc
spec:
  ports:
  - name: port-1
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: port-2
    port: 15090
    protocol: TCP
    targetPort: 15090
  selector:
    istio.io/rev: default
    run: auther-app
    security.istio.io/tlsMode: istio
    service.istio.io/canonical-name: external-app
    service.istio.io/canonical-revision: latest
status:
  loadBalancer: {}
