apiVersion: v1
kind: Pod
metadata:
  labels:
    run: keycloak
  name: keycloak
spec:
  containers:
  - image: jboss/keycloak
    name: keycloak
    env:
      - name: KEYCLOAK_USER
        value: admin
      - name: KEYCLOAK_PASSWORD
        value: password
    ports:
      - containerPort: 8080
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
